package tokenizer

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// testdata/world-corpus.* is generated by
// test/round3/token-census/emit_go_fixture.py from the same deterministic
// generators that built every probe and e2e corpus. The truth counts come from
// the Python trie tokenizer (test/probes/common/rwkv_tokenizer.py), which is
// the implementation the BFCL pysidecar count_tokens op verified against as
// well (round-3 census cross-check: 0 mismatches on shared texts).
const (
	fixtureTexts  = "world-corpus.jsonl"
	fixtureCounts = "world-corpus-counts.json"
)

func openTestWorld(t *testing.T) *World {
	t.Helper()
	vocab := findVocab(t)
	world, err := OpenWorld(vocab)
	if err != nil {
		t.Fatalf("OpenWorld(%s): %v", vocab, err)
	}
	return world
}

func findVocab(t *testing.T) string {
	t.Helper()
	candidates := []string{
		filepath.Join("..", "..", "third_party", "rwkv-mobile", "assets",
			"rwkv_vocab_v20230424.txt"),
		"third_party/rwkv-mobile/assets/rwkv_vocab_v20230424.txt",
	}
	for _, candidate := range candidates {
		if _, err := os.Stat(candidate); err == nil {
			absolute, err := filepath.Abs(candidate)
			if err != nil {
				t.Fatalf("abs path: %v", err)
			}
			return absolute
		}
	}
	t.Skipf("World vocab not found (run `git submodule update --init`)")
	return ""
}

func TestWorldMatchesPythonCountsOnCorpus(t *testing.T) {
	world := openTestWorld(t)
	countsFile, err := os.Open(filepath.Join("testdata", fixtureCounts))
	if err != nil {
		t.Skipf("fixture counts not found: %v", err)
	}
	defer countsFile.Close()
	var fixture struct {
		VocabSHA256 string         `json:"vocab_sha256"`
		NTexts      int            `json:"n_texts"`
		Counts      map[string]int `json:"counts"`
	}
	if err := json.NewDecoder(countsFile).Decode(&fixture); err != nil {
		t.Fatalf("decode fixture counts: %v", err)
	}
	if world.SHA256() != fixture.VocabSHA256 {
		t.Fatalf("vocab sha256 mismatch: Go %s != fixture %s",
			world.SHA256(), fixture.VocabSHA256)
	}
	textsFile, err := os.Open(filepath.Join("testdata", fixtureTexts))
	if err != nil {
		t.Skipf("fixture texts not found: %v", err)
	}
	defer textsFile.Close()
	decoder := json.NewDecoder(textsFile)
	checked := 0
	for decoder.More() {
		var row struct {
			ID   string `json:"id"`
			Text string `json:"text"`
		}
		if err := decoder.Decode(&row); err != nil {
			t.Fatalf("decode fixture text %d: %v", checked, err)
		}
		want, ok := fixture.Counts[row.ID]
		if !ok {
			t.Fatalf("fixture text %s has no truth count", row.ID)
		}
		if got := world.Count(row.Text); got != want {
			t.Fatalf("%s: Go count %d != Python count %d", row.ID, got, want)
		}
		// Round-trip: decoding must reproduce the text byte-for-byte.
		ids := world.Encode(row.Text)
		if len(ids) != want {
			t.Fatalf("%s: Encode length %d != Count %d", row.ID, len(ids), want)
		}
		checked++
	}
	if checked != fixture.NTexts {
		t.Fatalf("checked %d texts, fixture has %d", checked, fixture.NTexts)
	}
}

func TestWorldCountsSmallSamples(t *testing.T) {
	world := openTestWorld(t)
	// Exact pins from the round-3 census Python runs.
	pins := map[string]int{
		"The quick brown fox jumps over the lazy dog. Observatory operations were audited in 2024.": 19,
		"中国科学院国家天文台在2024年发布了新的巡天数据，总计6,412人次参与观测。":                                                  37,
		"def align_frames(frames, reference):\n    offsets = []\n    return offsets\n":              18,
		"- Item 3: status verified on site, reference 412\n- Item 4: logs uploaded\n":               20,
		"Row 17: the entry mirrors the standard layout of the catalogue. Status remains unchanged.": 17,
		"混合文本：English mixed with 中文与数字 6412 和标点！":                                                   21,
	}
	for text, want := range pins {
		if got := world.Count(text); got != want {
			t.Fatalf("Count(%q) = %d, want %d", text, got, want)
		}
	}
	if got := world.Count("<EOD>"); got != 1 {
		t.Fatalf("Count(<EOD>) = %d, want 1 (trie hpp token 0)", got)
	}
}

func TestParseLiterals(t *testing.T) {
	cases := []struct {
		raw  string
		want string
	}{
		{"'\\x00'", "\x00"},
		{"'\\t'", "\t"},
		{"'\\n'", "\n"},
		{"'\\\\'", "\\"},
		{"'\\''", "'"},
		{"'中'", "中"},
		{"'\\u4e2d'", "中"},
		{"'\\\\u4e2d'", "\\u4e2d"},
		{"'\\x41\\x42'", "AB"},
		{"\"'ll\"", "'ll"},
	}
	for _, tc := range cases {
		got, err := parseStrLiteral(tc.raw)
		if err != nil {
			t.Fatalf("parseStrLiteral(%s): %v", tc.raw, err)
		}
		if string(got) != tc.want {
			t.Fatalf("parseStrLiteral(%s) = %q, want %q", tc.raw, got, tc.want)
		}
	}
	// Bytes literals decode \xNN as one raw byte, not a Unicode codepoint.
	got, err := parseBytesLiteral(`b'\x80'`)
	if err != nil {
		t.Fatalf("parseBytesLiteral: %v", err)
	}
	if len(got) != 1 || got[0] != 0x80 {
		t.Fatalf("parseBytesLiteral(b'\\x80') = %v, want [0x80]", got)
	}
}
