#!/usr/bin/env python3
"""Generate an INDEX.md table for a directory tree of eval runs.

Walks ROOT up to two levels deep, treats every directory containing
run.json / summary.json / per_case_scores.jsonl as one run, and writes
ROOT/INDEX.md with one row per run. Handles the current harness summary
schema (summary.json -> metrics.task_success / pass_mean) and the older
BFCL-harness layout (per_case_scores.jsonl accuracy). Bundle directories
(SUMMARY.md, no manifest) are listed with a "bundle" marker.

Usage:
  python3 index_runs.py [ROOT]   # writes ROOT/INDEX.md
"""
import datetime
import json
import pathlib
import sys

MARKERS = ("run.json", "summary.json", "per_case_scores.jsonl")


def load(path):
    try:
        with open(path) as handle:
            return json.load(handle)
    except Exception:
        return None


def pick(*values):
    for value in values:
        if value:
            return value
    return None


def model_name(run, path):
    model = (run or {}).get("model")
    if isinstance(model, dict):
        return pick(model.get("identifier"), model.get("name"), model.get("id"))
    return pick(model, (run or {}).get("model_id"), path.name if path.name.startswith("run") else None)


def bank_name(run, path):
    return pick((run or {}).get("suite"), (run or {}).get("tool_catalog"),
                (run or {}).get("suite_name"), path.parent.name)


def harness_name(run):
    value = pick((run or {}).get("harness_version"), (run or {}).get("harness"),
                 (run or {}).get("schema_version"))
    if isinstance(value, dict):
        value = pick(value.get("version"), value.get("schema_version"))
    return value


def case_count(run, summ):
    for source in (run, summ):
        cases = (source or {}).get("cases")
        if isinstance(cases, list) and cases:
            return len(cases)
        if isinstance(cases, dict) and "cases" in (source or {}):
            return len(cases)
    return None


def pass_rate(dirpath, summ):
    metrics = (summ or {}).get("metrics") or {}
    ts = metrics.get("task_success")
    if isinstance(ts, dict) and ts.get("total"):
        return "%s/%s (%.1f%%)" % (ts.get("correct"), ts.get("total"), 100 * ts.get("rate", 0))
    mean = (summ or {}).get("pass_mean")
    if isinstance(mean, (int, float)):
        return "%.1f%%" % (100 * mean)
    # Older BFCL-harness runs: mean per-case accuracy over per_case_scores.jsonl.
    scores = dirpath / "per_case_scores.jsonl"
    if scores.exists():
        total, valid = 0, 0
        try:
            with open(scores) as handle:
                for line in handle:
                    row = json.loads(line)
                    if isinstance(row.get("accuracy"), (int, float)):
                        total += row["accuracy"]
                        valid += 1
            if valid:
                return "%.1f%% (per-case acc mean)" % (100 * total / valid)
        except Exception:
            pass
    return "—"


def run_date(dirpath, run):
    stamp = pick((run or {}).get("completed_at"), (run or {}).get("started_at"),
                 (run or {}).get("date"))
    if isinstance(stamp, str):
        return stamp[:19].replace("T", " ")
    mtime = dirpath.stat().st_mtime
    return datetime.datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M")


def find_run_dirs(root):
    """Run dirs and family dirs (nested one level), plus bundle dirs."""
    entries = []
    for depth in (0, 1, 2):
        for path in sorted(root.glob("*" + "/*" * depth)):
            if not path.is_dir():
                continue
            if any((path / marker).exists() for marker in MARKERS):
                entries.append(path)
            elif (path / "SUMMARY.md").exists() and path.name.startswith("bundle"):
                entries.append(path)
    # Deduplicate: a run dir found via a deeper glob is listed once.
    return sorted(set(entries), key=lambda p: p.as_posix())


def main():
    root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(".")
    rows = []
    for path in find_run_dirs(root):
        run = load(path / "run.json")
        summ = load(path / "summary.json")
        is_bundle = run is None and summ is None
        rows.append({
            "run": path.relative_to(root).as_posix(),
            "date": run_date(path, run),
            "bank": "bundle" if is_bundle else (bank_name(run, path) or "—"),
            "model": model_name(run, path) or "—",
            "cases": case_count(run, summ) or "—",
            "pass": "—" if is_bundle else pass_rate(path, summ),
            "harness": harness_name(run) or "—",
        })
    rows.sort(key=lambda row: row["date"])
    out = ["# Run index", "",
           "Generated by `tools/index_runs.py` — one row per run directory;",
           "regenerate with `python3 tools/index_runs.py <this directory>`. Config",
           "details (wire, sampling, case definitions) live in each run's `run.json`.", "",
           "| Run | Date | Bank | Model | Cases | Pass | Harness |",
           "|---|---|---|---|---|---|---|"]
    for row in rows:
        out.append("| `{run}` | {date} | {bank} | {model} | {cases} | {pass} | {harness} |".format(**row))
    (root / "INDEX.md").write_text("\n".join(out) + "\n")
    print("wrote %s (%d rows)" % (root / "INDEX.md", len(rows)))


if __name__ == "__main__":
    main()
