// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * AgentProtocol selects the product-facing tool transcript.
 */
export enum AgentProtocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AgentProtocolMarkdown = "markdown",
    AgentProtocolXML = "xml",
};

/**
 * Config configures one local or remote model provider. Secret fields are
 * accepted as input but are never included in Status.
 */
export class Config {
    "provider": Provider;
    "model": string;
    "endpoint"?: string;
    "apiKey"?: string;
    "password"?: string;
    "headers"?: { [_ in string]?: string };
    "tokenizerPath"?: string;
    "backend"?: string;
    "nativeProvider"?: string;
    "thinking"?: string;
    "agentProtocol"?: AgentProtocol;
    "maxSteps"?: number;
    "maxTokens"?: number;
    "routeMaxTokens"?: number;
    "temperature"?: number;
    "topK"?: number;
    "topP"?: number;
    "presencePenalty"?: number;
    "frequencyPenalty"?: number;
    "penaltyDecay"?: number;
    "chatThinking"?: string;
    "chatPromptMode"?: string;
    "chatTokenLimit"?: string;
    "stream"?: boolean | null;
    "rwkvStopTokens"?: string;
    "progressiveTools"?: boolean | null;
    "enableWeb"?: boolean;
    "braveApiKey"?: string;
    "braveEndpoint"?: string;
    "tavilyApiKey"?: string;
    "tavilyEndpoint"?: string;
    "enableSubagents"?: boolean;
    "maxActiveBatch"?: number;
    "remoteBatchWaitMs"?: number;
    "subagentMaxParallel"?: number;
    "subagentMaxSteps"?: number;
    "subagentTimeoutSeconds"?: number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = Provider.$zero;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField5_0($$parsedSource["headers"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ModelState describes the lifecycle state visible to clients.
 */
export enum ModelState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModelIdle = "idle",
    ModelLoading = "loading",
    ModelReady = "ready",
    ModelError = "error",
};

/**
 * Provider selects the continuation implementation used by a Service.
 */
export enum Provider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderLocal = "local",
    ProviderChatCompletions = "chat-completions",
    ProviderRWKVLightning = "rwkv-lightning",
};

/**
 * RemoteModel is one model returned by an OpenAI-compatible models endpoint.
 */
export class RemoteModel {
    "id": string;

    /** Creates a new RemoteModel instance. */
    constructor($$source: Partial<RemoteModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteModel instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteModel($$parsedSource as Partial<RemoteModel>);
    }
}

/**
 * Result is one committed Agent turn.
 */
export class Result {
    "output": string;
    "route"?: string;
    "bundles"?: string[];
    "steps": Step[];
    "duration": time$0.Duration;
    "durationMs": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bundles" in $$parsedSource) {
            $$parsedSource["bundles"] = $$createField2_0($$parsedSource["bundles"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField3_0($$parsedSource["steps"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Status is the non-secret model state displayed by clients.
 */
export class Status {
    "state": ModelState;
    "provider"?: Provider;
    "model"?: string;
    "endpoint"?: string;
    "backend"?: string;
    "format"?: string;
    "architecture"?: string;
    "workspace": string;
    "message"?: string;
    "headerNames"?: string[];
    "hasApiKey": boolean;
    "updatedAt": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("state" in $$source)) {
            this["state"] = ModelState.$zero;
        }
        if (!("workspace" in $$source)) {
            this["workspace"] = "";
        }
        if (!("hasApiKey" in $$source)) {
            this["hasApiKey"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headerNames" in $$parsedSource) {
            $$parsedSource["headerNames"] = $$createField9_0($$parsedSource["headerNames"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * Step is the public trace summary for one model action.
 */
export class Step {
    "number": number;
    "stage": string;
    "modelOutput"?: string;
    "finishReason"?: string;
    "actionType"?: string;
    "tool"?: string;
    "toolArguments"?: string;
    "toolResult"?: string;
    "toolExecuted"?: boolean;
    "toolError"?: string;

    /** Creates a new Step instance. */
    constructor($$source: Partial<Step> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     */
    static createFrom($$source: any = {}): Step {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Step($$parsedSource as Partial<Step>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Step.createFrom;
const $$createType3 = $Create.Array($$createType2);
