// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * AgentPromptPreview is the read-only system prompt view behind the settings
 * preview: what a session with this configuration would send, assembled for
 * the service workspace with the full depth-0 tool catalog.
 */
export class AgentPromptPreview {
    "control": string;
    "responseControl": string;
    "toolNames": string[];
    "protocolId": string;
    "rendererId": string;
    "thinkingMode": string;
    "native": boolean;

    /** Creates a new AgentPromptPreview instance. */
    constructor($$source: Partial<AgentPromptPreview> = {}) {
        if (!("control" in $$source)) {
            this["control"] = "";
        }
        if (!("responseControl" in $$source)) {
            this["responseControl"] = "";
        }
        if (!("toolNames" in $$source)) {
            this["toolNames"] = [];
        }
        if (!("protocolId" in $$source)) {
            this["protocolId"] = "";
        }
        if (!("rendererId" in $$source)) {
            this["rendererId"] = "";
        }
        if (!("thinkingMode" in $$source)) {
            this["thinkingMode"] = "";
        }
        if (!("native" in $$source)) {
            this["native"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentPromptPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentPromptPreview {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolNames" in $$parsedSource) {
            $$parsedSource["toolNames"] = $$createField2_0($$parsedSource["toolNames"]);
        }
        return new AgentPromptPreview($$parsedSource as Partial<AgentPromptPreview>);
    }
}

/**
 * AgentProtocol selects the product-facing tool transcript. The zero value
 * resolves to XML; Markdown remains an explicit option.
 */
export enum AgentProtocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AgentProtocolMarkdown = "markdown",
    AgentProtocolXML = "xml",
};

/**
 * Config configures one local or remote model provider. Secret fields are
 * accepted as input but are never included in Status.
 */
export class Config {
    "provider": Provider;
    "model": string;
    "endpoint"?: string;
    "apiKey"?: string;
    "password"?: string;
    "headers"?: { [_ in string]?: string };
    "tokenizerPath"?: string;
    "backend"?: string;
    "nativeProvider"?: string;
    "thinking"?: string;
    "agentProtocol"?: AgentProtocol;

    /**
     * TaskControl is the user's free-text contract appended verbatim after the
     * transcript's system prompt ("Task-specific contract:" block). It is the
     * supported personalization surface; the protocol-owned instructions stay
     * immutable so the measured transcript contract cannot be broken here.
     */
    "taskControl"?: string;
    "semanticNoTool"?: boolean | null;
    "decisionFakeThink"?: boolean;
    "deepToolAnchor"?: boolean | null;
    "maxSteps"?: number;
    "maxTokens"?: number;
    "decisionMaxTokens"?: number;
    "routeMaxTokens"?: number;
    "tracePromptBytes"?: number | null;
    "temperature"?: number;
    "topK"?: number;
    "topP"?: number;
    "presencePenalty"?: number;
    "frequencyPenalty"?: number;
    "penaltyDecay"?: number;
    "chatThinking"?: string;
    "chatPromptMode"?: string;
    "chatTokenLimit"?: string;
    "stream"?: boolean | null;
    "rwkvStopTokens"?: string;

    /**
     * ProgressiveTools enables the optional capability Router. Nil defaults to
     * false so the XML decision stage owns tool selection directly.
     */
    "progressiveTools"?: boolean | null;
    "enableWeb"?: boolean;
    "braveApiKey"?: string;
    "braveEndpoint"?: string;
    "tavilyApiKey"?: string;
    "tavilyEndpoint"?: string;
    "enableSubagents"?: boolean;

    /**
     * CompressFetch enables query-aware compression of long web_fetch results
     * before they enter the agent transcript (PREFERENCES.md P5-1..P5-3).
     */
    "compressFetch"?: boolean;
    "maxActiveBatch"?: number;
    "remoteBatchWaitMs"?: number;
    "subagentMaxParallel"?: number;
    "subagentMaxSteps"?: number;
    "subagentTimeoutSeconds"?: number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = Provider.$zero;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField5_0($$parsedSource["headers"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ModelState describes the lifecycle state visible to clients.
 */
export enum ModelState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModelIdle = "idle",
    ModelLoading = "loading",
    ModelReady = "ready",
    ModelError = "error",
};

/**
 * PromptTrace is the bounded request snapshot that produced one model output.
 * It can contain local conversation and workspace content and is intended for
 * the local trajectory inspector, not telemetry.
 */
export class PromptTrace {
    "prompt": string;
    "bytes": number;
    "truncated"?: boolean;
    "assistantPrefix"?: string;
    "stops"?: string[];
    "maxOutputTokens"?: number;
    "toolsOffered"?: string[];

    /** Creates a new PromptTrace instance. */
    constructor($$source: Partial<PromptTrace> = {}) {
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTrace {
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stops" in $$parsedSource) {
            $$parsedSource["stops"] = $$createField4_0($$parsedSource["stops"]);
        }
        if ("toolsOffered" in $$parsedSource) {
            $$parsedSource["toolsOffered"] = $$createField6_0($$parsedSource["toolsOffered"]);
        }
        return new PromptTrace($$parsedSource as Partial<PromptTrace>);
    }
}

/**
 * Provider selects the continuation implementation used by a Service.
 */
export enum Provider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderLocal = "local",
    ProviderChatCompletions = "chat-completions",
    ProviderRWKVLightning = "rwkv-lightning",
};

/**
 * RemoteModel is one model returned by an OpenAI-compatible models endpoint.
 */
export class RemoteModel {
    "id": string;

    /** Creates a new RemoteModel instance. */
    constructor($$source: Partial<RemoteModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteModel instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteModel($$parsedSource as Partial<RemoteModel>);
    }
}

/**
 * Result is one committed Agent turn.
 */
export class Result {
    "output": string;
    "error"?: string;
    "originalOutput"?: string;
    "startedAtMs"?: number;
    "routeSteps"?: RouteStep[];
    "route"?: string;
    "bundles"?: string[];
    "steps": Step[];
    "answerContractRepaired"?: boolean;
    "answerViolations"?: string[];
    "forcedAnswerReason"?: string;
    "duration": time$0.Duration;
    "durationMs": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField4_0 = $$createType3;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType5;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routeSteps" in $$parsedSource) {
            $$parsedSource["routeSteps"] = $$createField4_0($$parsedSource["routeSteps"]);
        }
        if ("bundles" in $$parsedSource) {
            $$parsedSource["bundles"] = $$createField6_0($$parsedSource["bundles"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField7_0($$parsedSource["steps"]);
        }
        if ("answerViolations" in $$parsedSource) {
            $$parsedSource["answerViolations"] = $$createField9_0($$parsedSource["answerViolations"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * RouteStep records one routing generation, including correction retries.
 */
export class RouteStep {
    "attempt": number;
    "startedAtMs"?: number;
    "request"?: PromptTrace | null;
    "modelOutput"?: string;
    "route"?: string;
    "bundles"?: string[];
    "protocolError"?: string;
    "failedClosed"?: boolean;
    "durationMs"?: number;

    /** Creates a new RouteStep instance. */
    constructor($$source: Partial<RouteStep> = {}) {
        if (!("attempt" in $$source)) {
            this["attempt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteStep instance from a string or object.
     */
    static createFrom($$source: any = {}): RouteStep {
        const $$createField2_0 = $$createType7;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField2_0($$parsedSource["request"]);
        }
        if ("bundles" in $$parsedSource) {
            $$parsedSource["bundles"] = $$createField5_0($$parsedSource["bundles"]);
        }
        return new RouteStep($$parsedSource as Partial<RouteStep>);
    }
}

/**
 * Status is the non-secret model state displayed by clients.
 */
export class Status {
    "state": ModelState;
    "provider"?: Provider;
    "model"?: string;
    "endpoint"?: string;
    "backend"?: string;
    "format"?: string;
    "architecture"?: string;
    "workspace": string;
    "message"?: string;
    "headerNames"?: string[];
    "hasApiKey": boolean;
    "updatedAt": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("state" in $$source)) {
            this["state"] = ModelState.$zero;
        }
        if (!("workspace" in $$source)) {
            this["workspace"] = "";
        }
        if (!("hasApiKey" in $$source)) {
            this["hasApiKey"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headerNames" in $$parsedSource) {
            $$parsedSource["headerNames"] = $$createField9_0($$parsedSource["headerNames"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * Step is the public trace summary for one model action.
 */
export class Step {
    "number": number;
    "stage": string;
    "request"?: PromptTrace | null;
    "modelOutput"?: string;
    "finishReason"?: string;
    "usage": Usage;
    "startedAtMs"?: number;
    "modelDurationMs"?: number;
    "modelError"?: string;
    "actionType"?: string;
    "tool"?: string;
    "toolArguments"?: string;
    "toolResult"?: string;
    "toolExecuted"?: boolean;
    "toolEvidence"?: boolean;
    "toolUnavailable"?: boolean;
    "toolRejected"?: string;
    "toolError"?: string;
    "protocolError"?: string;
    "protocolRepaired"?: boolean;
    "stageViolation"?: boolean;
    "toolRetries"?: ToolRetryTrace[];
    "subagents"?: SubagentTrace[];
    "toolDurationMs"?: number;
    "toolStartedAtMs"?: number;
    "noToolRationale"?: string;
    "noToolAnswer"?: string;

    /** Creates a new Step instance. */
    constructor($$source: Partial<Step> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     */
    static createFrom($$source: any = {}): Step {
        const $$createField2_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        const $$createField21_0 = $$createType10;
        const $$createField22_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField2_0($$parsedSource["request"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField5_0($$parsedSource["usage"]);
        }
        if ("toolRetries" in $$parsedSource) {
            $$parsedSource["toolRetries"] = $$createField21_0($$parsedSource["toolRetries"]);
        }
        if ("subagents" in $$parsedSource) {
            $$parsedSource["subagents"] = $$createField22_0($$parsedSource["subagents"]);
        }
        return new Step($$parsedSource as Partial<Step>);
    }
}

/**
 * SubagentStep is one compact child tool invocation. Tool result bodies are
 * omitted so this trace is safe to retain in presentation storage.
 */
export class SubagentStep {
    "number": number;
    "tool": string;
    "arguments"?: string;
    "status": string;
    "error"?: string;
    "retries"?: ToolRetryTrace[];

    /** Creates a new SubagentStep instance. */
    constructor($$source: Partial<SubagentStep> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubagentStep instance from a string or object.
     */
    static createFrom($$source: any = {}): SubagentStep {
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("retries" in $$parsedSource) {
            $$parsedSource["retries"] = $$createField5_0($$parsedSource["retries"]);
        }
        return new SubagentStep($$parsedSource as Partial<SubagentStep>);
    }
}

/**
 * SubagentTrace is one delegated Agent run attached to its parent tool step.
 */
export class SubagentTrace {
    "index": number;
    "task": string;
    "status": string;
    "error"?: string;
    "route"?: string;
    "bundles"?: string[];
    "startedAtMs"?: number;
    "durationMs": number;
    "output"?: string;
    "sources"?: string[];
    "steps"?: SubagentStep[];

    /** Creates a new SubagentTrace instance. */
    constructor($$source: Partial<SubagentTrace> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubagentTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): SubagentTrace {
        const $$createField5_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bundles" in $$parsedSource) {
            $$parsedSource["bundles"] = $$createField5_0($$parsedSource["bundles"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField9_0($$parsedSource["sources"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField10_0($$parsedSource["steps"]);
        }
        return new SubagentTrace($$parsedSource as Partial<SubagentTrace>);
    }
}

export class ToolRetryTrace {
    "attempt": number;
    "maxAttempts": number;
    "statusCode"?: number;
    "delayMs": number;

    /** Creates a new ToolRetryTrace instance. */
    constructor($$source: Partial<ToolRetryTrace> = {}) {
        if (!("attempt" in $$source)) {
            this["attempt"] = 0;
        }
        if (!("maxAttempts" in $$source)) {
            this["maxAttempts"] = 0;
        }
        if (!("delayMs" in $$source)) {
            this["delayMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolRetryTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolRetryTrace {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolRetryTrace($$parsedSource as Partial<ToolRetryTrace>);
    }
}

/**
 * Usage is the token accounting reported by the configured provider. The
 * cache and reasoning breakdowns come from OpenAI-compatible usage details and
 * stay zero for the local and RWKV continuation backends.
 */
export class Usage {
    "promptTokens"?: number;
    "completionTokens"?: number;
    "cacheReadTokens"?: number;
    "cacheWriteTokens"?: number;
    "reasoningTokens"?: number;

    /** Creates a new Usage instance. */
    constructor($$source: Partial<Usage> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     */
    static createFrom($$source: any = {}): Usage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage($$parsedSource as Partial<Usage>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = RouteStep.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Step.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PromptTrace.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = Usage.createFrom;
const $$createType9 = ToolRetryTrace.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = SubagentTrace.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = SubagentStep.createFrom;
const $$createType14 = $Create.Array($$createType13);
