// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../api/models.js";

/**
 * SavedProvider 是一条可复用的"连接档案/预设"：配置一次、持久化，之后从下拉栏直接切换重连。
 */
export class SavedProvider {
    "id": string;
    "label": string;
    "config": api$0.Config;
    "lastUsedAt": string;

    /** Creates a new SavedProvider instance. */
    constructor($$source: Partial<SavedProvider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new api$0.Config());
        }
        if (!("lastUsedAt" in $$source)) {
            this["lastUsedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedProvider {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        return new SavedProvider($$parsedSource as Partial<SavedProvider>);
    }
}

// Private type creation functions
const $$createType0 = api$0.Config.createFrom;
