// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService binds durable application state to the public Agent API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateProvider 切换到一条已保存的连接档案：取出其 Config 后复用 Configure 完成连接并置为 active。
 */
export function ActivateProvider(id: string): $CancellablePromise<api$0.Status> {
    return $Call.ByID(537261178, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Bootstrap returns all durable state needed to hydrate the frontend.
 */
export function Bootstrap(): $CancellablePromise<$models.AppBootstrap> {
    return $Call.ByID(4177956144).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Chat runs and durably commits one Agent turn in the active conversation.
 */
export function Chat(prompt: string): $CancellablePromise<api$0.Result> {
    return $Call.ByID(3484087444, prompt).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ChooseWorkspace opens the platform-native directory picker. Server builds
 * return the Wails "file dialogs not available" error.
 */
export function ChooseWorkspace(): $CancellablePromise<$models.AppBootstrap> {
    return $Call.ByID(3272609536).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Close releases the current conversation and model provider.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2836621974);
}

/**
 * Configure replaces the active provider and persists the complete settings,
 * including credentials, in the XDG configuration file.
 */
export function Configure(config: api$0.Config): $CancellablePromise<api$0.Status> {
    return $Call.ByID(1065098514, config).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteConversation removes one saved conversation.
 */
export function DeleteConversation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1906186646, id);
}

/**
 * DeleteProvider 删除一条连接档案并返回刷新后的引导状态（不影响当前正在运行的会话）。
 */
export function DeleteProvider(id: string): $CancellablePromise<$models.AppBootstrap> {
    return $Call.ByID(3409054988, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportTrajectory shows a native save dialog and writes the given JSONL
 * content to the chosen path. Returns the written path, or "" when the user
 * cancels the dialog.
 */
export function ExportTrajectory(content: string): $CancellablePromise<string> {
    return $Call.ByID(179504977, content);
}

/**
 * ListRemoteModels verifies remote connectivity and returns model identifiers.
 */
export function ListRemoteModels(config: api$0.Config): $CancellablePromise<api$0.RemoteModel[]> {
    return $Call.ByID(3365822742, config).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * NewConversation starts a blank durable conversation while preserving the
 * configured provider.
 */
export function NewConversation(): $CancellablePromise<void> {
    return $Call.ByID(1069091331);
}

/**
 * OpenConversation selects an existing conversation for display and semantic
 * continuation. Its Harness transcript is restored lazily when the next turn
 * runs.
 */
export function OpenConversation(id: string): $CancellablePromise<$models.ConversationView> {
    return $Call.ByID(2245178561, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenWorkspace switches to an existing directory and unloads the current
 * provider. Persisted model settings remain available for reconnection.
 */
export function OpenWorkspace(path: string): $CancellablePromise<$models.AppBootstrap> {
    return $Call.ByID(928350323, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Status returns the current non-secret model state.
 */
export function Status(): $CancellablePromise<api$0.Status> {
    return $Call.ByID(838280468).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.Status.createFrom;
const $$createType1 = $models.AppBootstrap.createFrom;
const $$createType2 = api$0.Result.createFrom;
const $$createType3 = api$0.RemoteModel.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ConversationView.createFrom;
