// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the thin Wails binding over the public application API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../api/models.js";

/**
 * Chat runs one committed Agent turn in the active conversation.
 */
export function Chat(prompt: string): $CancellablePromise<api$0.Result> {
    return $Call.ByID(3484087444, prompt).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Close releases the current conversation and model provider.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2836621974);
}

/**
 * Configure replaces the active local or remote model provider.
 */
export function Configure(config: api$0.Config): $CancellablePromise<api$0.Status> {
    return $Call.ByID(1065098514, config).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListRemoteModels verifies remote connectivity and returns model identifiers.
 */
export function ListRemoteModels(config: api$0.Config): $CancellablePromise<api$0.RemoteModel[]> {
    return $Call.ByID(3365822742, config).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * NewConversation clears the current transcript while preserving the model.
 */
export function NewConversation(): $CancellablePromise<void> {
    return $Call.ByID(1069091331);
}

/**
 * Status returns the current non-secret model state.
 */
export function Status(): $CancellablePromise<api$0.Status> {
    return $Call.ByID(838280468).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = api$0.Result.createFrom;
const $$createType1 = api$0.Status.createFrom;
const $$createType2 = api$0.RemoteModel.createFrom;
const $$createType3 = $Create.Array($$createType2);
