// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../api/models.js";

export class AppBootstrap {
    "status": api$0.Status;
    "config": api$0.Config;
    "hasConfig": boolean;
    "conversations": ConversationSummary[];
    "conversation"?: ConversationView | null;
    "workspaces": WorkspaceItem[];
    "paths": StoragePaths;
    "warning"?: string;

    /** Creates a new AppBootstrap instance. */
    constructor($$source: Partial<AppBootstrap> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new api$0.Status());
        }
        if (!("config" in $$source)) {
            this["config"] = (new api$0.Config());
        }
        if (!("hasConfig" in $$source)) {
            this["hasConfig"] = false;
        }
        if (!("conversations" in $$source)) {
            this["conversations"] = [];
        }
        if (!("workspaces" in $$source)) {
            this["workspaces"] = [];
        }
        if (!("paths" in $$source)) {
            this["paths"] = (new StoragePaths());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppBootstrap instance from a string or object.
     */
    static createFrom($$source: any = {}): AppBootstrap {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        if ("conversations" in $$parsedSource) {
            $$parsedSource["conversations"] = $$createField3_0($$parsedSource["conversations"]);
        }
        if ("conversation" in $$parsedSource) {
            $$parsedSource["conversation"] = $$createField4_0($$parsedSource["conversation"]);
        }
        if ("workspaces" in $$parsedSource) {
            $$parsedSource["workspaces"] = $$createField5_0($$parsedSource["workspaces"]);
        }
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField6_0($$parsedSource["paths"]);
        }
        return new AppBootstrap($$parsedSource as Partial<AppBootstrap>);
    }
}

export class ConversationSummary {
    "id": string;
    "title": string;
    "updatedAt": string;

    /** Creates a new ConversationSummary instance. */
    constructor($$source: Partial<ConversationSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationSummary($$parsedSource as Partial<ConversationSummary>);
    }
}

export class ConversationView {
    "id": string;
    "title": string;
    "messages": DisplayMessage[];
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new ConversationView instance. */
    constructor($$source: Partial<ConversationView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationView {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new ConversationView($$parsedSource as Partial<ConversationView>);
    }
}

/**
 * DisplayMessage is one presentation-level message retained for the desktop
 * UI. The complete Harness transcript is stored separately and never trimmed
 * down to this view.
 */
export class DisplayMessage {
    "id": string;
    "role": string;
    "content": string;
    "meta"?: string;
    "trajectory"?: ToolTrace[];

    /** Creates a new DisplayMessage instance. */
    constructor($$source: Partial<DisplayMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): DisplayMessage {
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trajectory" in $$parsedSource) {
            $$parsedSource["trajectory"] = $$createField4_0($$parsedSource["trajectory"]);
        }
        return new DisplayMessage($$parsedSource as Partial<DisplayMessage>);
    }
}

export class StoragePaths {
    "configFile": string;
    "dataDirectory": string;
    "stateFile": string;
    "cacheDirectory": string;

    /** Creates a new StoragePaths instance. */
    constructor($$source: Partial<StoragePaths> = {}) {
        if (!("configFile" in $$source)) {
            this["configFile"] = "";
        }
        if (!("dataDirectory" in $$source)) {
            this["dataDirectory"] = "";
        }
        if (!("stateFile" in $$source)) {
            this["stateFile"] = "";
        }
        if (!("cacheDirectory" in $$source)) {
            this["cacheDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoragePaths instance from a string or object.
     */
    static createFrom($$source: any = {}): StoragePaths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoragePaths($$parsedSource as Partial<StoragePaths>);
    }
}

export class SubagentStep {
    "step": number;
    "tool": string;
    "arguments"?: string;
    "status": string;
    "error"?: string;
    "retries"?: ToolRetryTrace[];

    /** Creates a new SubagentStep instance. */
    constructor($$source: Partial<SubagentStep> = {}) {
        if (!("step" in $$source)) {
            this["step"] = 0;
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubagentStep instance from a string or object.
     */
    static createFrom($$source: any = {}): SubagentStep {
        const $$createField5_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("retries" in $$parsedSource) {
            $$parsedSource["retries"] = $$createField5_0($$parsedSource["retries"]);
        }
        return new SubagentStep($$parsedSource as Partial<SubagentStep>);
    }
}

export class SubagentTrace {
    "index": number;
    "task": string;
    "status": string;
    "error"?: string;
    "route"?: string;
    "bundles"?: string[];
    "durationMs": number;
    "output"?: string;
    "sources"?: string[];
    "steps"?: SubagentStep[];

    /** Creates a new SubagentTrace instance. */
    constructor($$source: Partial<SubagentTrace> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubagentTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): SubagentTrace {
        const $$createField5_0 = $$createType15;
        const $$createField8_0 = $$createType15;
        const $$createField9_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bundles" in $$parsedSource) {
            $$parsedSource["bundles"] = $$createField5_0($$parsedSource["bundles"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField8_0($$parsedSource["sources"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField9_0($$parsedSource["steps"]);
        }
        return new SubagentTrace($$parsedSource as Partial<SubagentTrace>);
    }
}

export class ToolRetryTrace {
    "attempt": number;
    "maxAttempts": number;
    "statusCode"?: number;
    "delayMs": number;

    /** Creates a new ToolRetryTrace instance. */
    constructor($$source: Partial<ToolRetryTrace> = {}) {
        if (!("attempt" in $$source)) {
            this["attempt"] = 0;
        }
        if (!("maxAttempts" in $$source)) {
            this["maxAttempts"] = 0;
        }
        if (!("delayMs" in $$source)) {
            this["delayMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolRetryTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolRetryTrace {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolRetryTrace($$parsedSource as Partial<ToolRetryTrace>);
    }
}

export class ToolTrace {
    "step": number;
    "tool": string;
    "arguments"?: string;
    "status": string;
    "error"?: string;
    "retries"?: ToolRetryTrace[];
    "subagents"?: SubagentTrace[];

    /** Creates a new ToolTrace instance. */
    constructor($$source: Partial<ToolTrace> = {}) {
        if (!("step" in $$source)) {
            this["step"] = 0;
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolTrace {
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("retries" in $$parsedSource) {
            $$parsedSource["retries"] = $$createField5_0($$parsedSource["retries"]);
        }
        if ("subagents" in $$parsedSource) {
            $$parsedSource["subagents"] = $$createField6_0($$parsedSource["subagents"]);
        }
        return new ToolTrace($$parsedSource as Partial<ToolTrace>);
    }
}

export class WorkspaceItem {
    "path": string;
    "name": string;
    "available": boolean;
    "active": boolean;

    /** Creates a new WorkspaceItem instance. */
    constructor($$source: Partial<WorkspaceItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceItem($$parsedSource as Partial<WorkspaceItem>);
    }
}

// Private type creation functions
const $$createType0 = api$0.Status.createFrom;
const $$createType1 = api$0.Config.createFrom;
const $$createType2 = ConversationSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ConversationView.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = WorkspaceItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = StoragePaths.createFrom;
const $$createType9 = DisplayMessage.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ToolTrace.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ToolRetryTrace.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = SubagentStep.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = SubagentTrace.createFrom;
const $$createType19 = $Create.Array($$createType18);
