// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appstorage$0 from "../../internal/appstorage/models.js";

export class AppBootstrap {
    "status": api$0.Status;
    "config": api$0.Config;
    "hasConfig": boolean;
    "providers": appstorage$0.SavedProvider[];
    "activeProviderId"?: string;
    "runtimeProviderId"?: string;
    "conversations": ConversationSummary[];
    "conversation"?: ConversationView | null;
    "workspaces": WorkspaceItem[];
    "paths": StoragePaths;
    "warning"?: string;

    /** Creates a new AppBootstrap instance. */
    constructor($$source: Partial<AppBootstrap> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new api$0.Status());
        }
        if (!("config" in $$source)) {
            this["config"] = (new api$0.Config());
        }
        if (!("hasConfig" in $$source)) {
            this["hasConfig"] = false;
        }
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("conversations" in $$source)) {
            this["conversations"] = [];
        }
        if (!("workspaces" in $$source)) {
            this["workspaces"] = [];
        }
        if (!("paths" in $$source)) {
            this["paths"] = (new StoragePaths());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppBootstrap instance from a string or object.
     */
    static createFrom($$source: any = {}): AppBootstrap {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField3_0($$parsedSource["providers"]);
        }
        if ("conversations" in $$parsedSource) {
            $$parsedSource["conversations"] = $$createField6_0($$parsedSource["conversations"]);
        }
        if ("conversation" in $$parsedSource) {
            $$parsedSource["conversation"] = $$createField7_0($$parsedSource["conversation"]);
        }
        if ("workspaces" in $$parsedSource) {
            $$parsedSource["workspaces"] = $$createField8_0($$parsedSource["workspaces"]);
        }
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField9_0($$parsedSource["paths"]);
        }
        return new AppBootstrap($$parsedSource as Partial<AppBootstrap>);
    }
}

export class ConversationSummary {
    "id": string;
    "title": string;
    "updatedAt": string;

    /** Creates a new ConversationSummary instance. */
    constructor($$source: Partial<ConversationSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationSummary($$parsedSource as Partial<ConversationSummary>);
    }
}

export class ConversationView {
    "id": string;
    "title": string;
    "messages": DisplayMessage[];
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new ConversationView instance. */
    constructor($$source: Partial<ConversationView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationView {
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new ConversationView($$parsedSource as Partial<ConversationView>);
    }
}

/**
 * The presentation message and tool-trace shapes are owned by appstorage (the
 * same values are persisted and served to the UI verbatim); these aliases keep
 * the short names the UI layer reads. DisplayMessage is one presentation-level
 * message retained for the desktop UI; the complete Harness transcript is
 * stored separately and never trimmed down to this view.
 */
export const DisplayMessage = appstorage$0.DisplayMessage;

/**
 * The presentation message and tool-trace shapes are owned by appstorage (the
 * same values are persisted and served to the UI verbatim); these aliases keep
 * the short names the UI layer reads. DisplayMessage is one presentation-level
 * message retained for the desktop UI; the complete Harness transcript is
 * stored separately and never trimmed down to this view.
 */
export type DisplayMessage = appstorage$0.DisplayMessage;

export class StoragePaths {
    "configFile": string;
    "dataDirectory": string;
    "stateFile": string;
    "cacheDirectory": string;

    /** Creates a new StoragePaths instance. */
    constructor($$source: Partial<StoragePaths> = {}) {
        if (!("configFile" in $$source)) {
            this["configFile"] = "";
        }
        if (!("dataDirectory" in $$source)) {
            this["dataDirectory"] = "";
        }
        if (!("stateFile" in $$source)) {
            this["stateFile"] = "";
        }
        if (!("cacheDirectory" in $$source)) {
            this["cacheDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoragePaths instance from a string or object.
     */
    static createFrom($$source: any = {}): StoragePaths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoragePaths($$parsedSource as Partial<StoragePaths>);
    }
}

export class WorkspaceItem {
    "path": string;
    "name": string;
    "available": boolean;
    "active": boolean;

    /** Creates a new WorkspaceItem instance. */
    constructor($$source: Partial<WorkspaceItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceItem($$parsedSource as Partial<WorkspaceItem>);
    }
}

// Private type creation functions
const $$createType0 = api$0.Status.createFrom;
const $$createType1 = api$0.Config.createFrom;
const $$createType2 = appstorage$0.SavedProvider.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ConversationSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ConversationView.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = WorkspaceItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = StoragePaths.createFrom;
const $$createType11 = appstorage$0.DisplayMessage.createFrom;
const $$createType12 = $Create.Array($$createType11);
